/** Format milliseconds into human-readable duration */
export function formatDuration(ms: number): string {
  const sec = ms / 1000
  if (sec < 60) return `${sec.toFixed(1)}s`
  if (sec < 3600) {
    const m = Math.floor(sec / 60)
    const s = Math.round(sec % 60)
    return s > 0 ? `${m}m ${s}s` : `${m}m`
  }
  const h = Math.floor(sec / 3600)
  const m = Math.round((sec % 3600) / 60)
  return m > 0 ? `${h}h ${m}m` : `${h}h`
}

/** Compact format — no seconds component for durations over 1min */
export function formatDurationCompact(ms: number): string {
  const sec = ms / 1000
  if (sec < 60) return `${sec.toFixed(1)}s`
  if (sec < 3600) return `${Math.round(sec / 60)}m`
  const h = Math.floor(sec / 3600)
  const m = Math.round((sec % 3600) / 60)
  return m > 0 ? `${h}h${m}m` : `${h}h`
}

/** Format seconds into human-readable duration */
export function formatSeconds(sec: number): string {
  return formatDuration(sec * 1000)
}

/** Format character count as human-readable (12k, 1.2M) */
export function formatChars(chars: number): string {
  if (chars < 1000) return String(chars)
  if (chars < 1000000) return `${(chars / 1000).toFixed(1)}k`
  return `${(chars / 1000000).toFixed(1)}M`
}

/** Format token count as human-readable (1.2k, 3.4M) */
export function formatTokenCount(tokens: number): string {
  if (tokens < 1000) return String(tokens)
  if (tokens < 1000000) return `${(tokens / 1000).toFixed(1)}k`
  return `${(tokens / 1000000).toFixed(1)}M`
}

/**
 * Estimate cost from input/output characters using model pricing.
 * Chars → tokens: ~4 chars per token for English.
 * Default: Sonnet 4 ($3/MTok input, $15/MTok output)
 */
const CHARS_PER_TOKEN = 4
const INPUT_COST_PER_MTOK = 3    // $/MTok — tool responses fed back to model
const OUTPUT_COST_PER_MTOK = 15  // $/MTok — tool inputs generated by model

export function estimateCostFromIO(inputChars: number, outputChars: number): number {
  const inputTokens = outputChars / CHARS_PER_TOKEN   // tool_response → model input
  const outputTokens = inputChars / CHARS_PER_TOKEN   // tool_input → model output
  return (inputTokens * INPUT_COST_PER_MTOK + outputTokens * OUTPUT_COST_PER_MTOK) / 1_000_000
}

export function formatCost(cost: number): string {
  if (cost < 0.001) return '<$0.01'
  if (cost < 0.01) return `$${cost.toFixed(3)}`
  return `$${cost.toFixed(2)}`
}

/** Shorthand: estimate cost from total chars (assumes 50/50 in/out split) */
export function estimateCost(chars: number): string {
  return formatCost(estimateCostFromIO(chars / 2, chars / 2))
}
